version: "3.7"

services:
  postgres:
    image: postgres
    user: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=artemis_dev
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    
